### PR TITLE
err renamed to exception

### PR DESCRIPTION
**Pull request by nwolverson**
ala https://github.com/purescript/purescript-exceptions/commit/ebb95a4ebe033b2f62feed8833a26fd352595107

### CODE REVIEW

**Comment by paf31** [comment]
Thanks - I suppose this must be a breaking change. Do you know if there are any dependent libraries which need to be updated?

**Comment by nwolverson** [comment]
I didn't spot any other instances of this being missed, but of course anything dependant on this could have a knock-on issue. Don't know how to search for things that depend on this.

**Comment by kRITZCREEK** [comment]
anything left to do here?

**Comment by paf31** [comment]
> anything left to do here?

Just need to figure out what this breaks and plan a breaking release.

**Comment by hdgarrood** [comment]
Can we use psc-package to check whether this breaks anything?

**Comment by hdgarrood** [comment]
Also, could we also change `chdir` in this PR too? `chdir` currently uses the old `err :: EXCEPTION` too.

**Comment by nwolverson** [comment]
@hdgarrood this PR already changes `chdir`?

**Comment by hdgarrood** [comment]
Oops, so it does!

**Comment by hdgarrood** [comment]
package-sets says the only downstream libraries are node-readline and spec, neither of which have any dependencies inside the package set themselves, so I'll merge this and update node-readline after I've made a new release of this library. Thanks!

**Pull request merged**
